### ISSUE TITLE
Connected components not working with react-hot-loader

### ISSUE THREAD

**Issue by edwjusti** [developit/unistore#116]
Components wrapped with connect are not updated after a hot reload, only components without the connect wrapper get their hot updates.

**Comment by developit** [comment]
Is this with React, or Preact?

**Comment by edwjusti** [comment]
React

**Comment by developit** [comment]
This is likely fixed by 10282582b21c1082cabc99501b81c5b165766db4.

**Comment by developit** [comment]
Released as [3.2.0](https://github.com/developit/unistore/releases/tag/3.2.0).

**Comment by edwjusti** [comment]
I'm sorry for taking so long to answer, but this issue is still there with the latest release. However I was able to mitigate the issue by rewriting the connect function using classes, the following code receives updates properly:

```javascript
export function connect(mapToProps, actions) {
  if (typeof mapToProps !== 'function') {
    mapToProps = select(mapToProps || []);
  }
  
  return Child => class Wrapper extends PureComponent {
    state = mapToProps(store.getState());

    update = state => this.setState(mapToProps(state));

    boundActions = actions ? mapActions(actions, store) : { store };

    componentWillMount() {
      store.subscribe(this.update);
    }

    componentWillUnmount() {
      store.unsubscribe(this.update);
    }

    render() {
      return createElement(
        Child,
        Object.assign(this.boundActions, this.props, this.state)
      );
    }
  };
}
```
